### ISSUE TITLE
Add `repr(transparent)` to VolatileCell

### ISSUE THREAD

**Issue by garasubo** [japaric/volatile-register#8]
Same as https://github.com/japaric/vcell/issues/5, and maybe similar to #5 
`RW`, `RW` and `WO` are used in ABI sensitive codes. So, it would be better to add `repr(transparent)` to those struct.

Ref: https://doc.rust-lang.org/nomicon/other-reprs.html

**Comment by Dirbaio** [comment]
fixed in #12
